### ISSUE TITLE
Question about parentheses (corrected: quotes)

### ISSUE THREAD

**Issue by stephanstapel** [jamesholcomb/InfluxDB.Net#2]
Hi,

When writing data to InfluxDB using your version of the library, tags and fields get parentheses. Please see the image for field value inserted via command line/ admin interface without parentheses and insertion via C# with parentheses:

![image](https://cloud.githubusercontent.com/assets/2912080/9098030/a61f7472-3bc7-11e5-91e6-9723135c6a1e.png)

The code I basically used is:

```
Point p = new Point()
                {
                    Name = "humidity",
                    Tags = new Dictionary<string, object>()
                    {
                        {  "my-tag", "3" }
                    },
                    Fields = new Dictionary<string, object>()
                    {
                        { "value", 10 }
                    },
                    Timestamp = DateTime.Now.AddMinutes(-i)
                };

```

is this a bug or a feature?

**Comment by jamesholcomb** [comment]
I didn't see any parenthesis in your screenshot. Can you provide a test to reproduce?

**Comment by stephanstapel** [comment]
sorry, that was a translation mistake. I wanted to say: double quotes!

**Comment by jamesholcomb** [comment]
Influxdb version?

**Comment by stephanstapel** [comment]
I built it from source on Windows on July 30th, so it must be 0.9.2.1+

**Comment by stephanstapel** [comment]
In the meantime I downloaded current InfluxDB code and the issue is still present. It seems that I can't select theses quoted fields correctly which hinders me to use Grafana

**Comment by jamesholcomb** [comment]
Couple of related changes...
1. The Tags dictionary is now `<string, string>` (tag keys and values must be `string` according to line protocol)
2. Tag and field keys that contain a hyphen (dash) do not work.  I think this is a bug in InfluxDb.  The tests were changed to use an underscore.

**Comment by stephanstapel** [comment]
looks good now, thanks for the fix!
